name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Core Tests
        run: |
          cd core
          make test

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.45

      - name: Build WebAssembly
        run: |
          cd bindings/javascript
          make clean
          make

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run JavaScript Tests
        run: |
          cd bindings/javascript
          npm test
