name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v24

      - name: Build
        run: |
          nix develop -c make build

      - name: Test
        run: |
          nix develop -c make test